import './globals.css'
import { Rubik } from 'next/font/google'
import Navbar from "@/app/components/Navbar";

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Next HelpDesk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
      <Navbar />
      <div className="main-children">
        {children}
      </div>
      </body>
    </html>
  )
}
